version: "3"

services:
  web:
    container_name: arcanesoft_web
    build: ./.docker/build/nginx
    volumes:
      - ./:/var/www/html/
      - ./.docker/build/nginx/conf.d:/etc/nginx/conf.d
    links:
      - php
    ports:
      - 8000:80
    working_dir: /var/www/html/
    restart: on-failure

  php:
    container_name: arcanesoft_php
    build: ./.docker/build/php
    volumes:
      - ./:/var/www/html/
    working_dir: /var/www/html/
    environment:
      - APP_URL="http://arcanesoft.test:8000"
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=arcanesoft
      - DB_USERNAME=admin
      - DB_PASSWORD=password
      - CACHE_DRIVER=redis
      - QUEUE_DRIVER=redis
      - REDIS_HOST=redis
    links:
      - db
      - redis
    restart: on-failure

  db:
    container_name: arcanesoft_db
    build: ./.docker/build/mysql
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 33060:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    restart: on-failure

  redis:
    container_name: arcanesoft_redis
    image: redis:alpine
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
    restart: on-failure

  redis-commander:
    container_name: arcanesoft_redis_commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    links:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 8081:8081
    restart: on-failure

volumes:
  db_data:
  redis_data:
