version: "3"

services:
    web:
        container_name: arcanesoft_web
        build: ./.docker/build/nginx
        volumes:
            - ./:/var/www/html/
            - ./.docker/build/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - php
        ports:
            - "80:80"
        working_dir: /var/www/html/

    php:
        container_name: arcanesoft_php
        build: ./.docker/build/php
        volumes:
            - ./:/var/www/html/
            - ./vendor:/var/www/html/vendor:delegated
            - ./node_modules:/var/www/html/node_modules:delegated
        working_dir: /var/www/html/
        environment:
            APP_URL: "http://arcanesoft.test:8000"
            DB_CONNECTION: "mysql"
            DB_HOST: "db"
            DB_PORT: "3306"
            DB_DATABASE: "arcanesoft"
            DB_USERNAME: "admin"
            DB_PASSWORD: "password"
            CACHE_DRIVER: "redis"
            QUEUE_DRIVER: "redis"
            REDIS_HOST: "redis"
        depends_on:
            - db
            - redis

    db:
        container_name: arcanesoft_db
        build: ./.docker/build/mysql
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

    mailhog:
        container_name: arcanesoft_mailhog
        image: mailhog/mailhog:latest
        ports:
            - "1025:1025"
            - "8025:8025"

    redis:
        container_name: arcanesoft_redis
        image: redis:alpine
        volumes:
            - redis_data:/data
        ports:
            - "6379:6379"

#    redis-commander:
#        container_name: arcanesoft_redis_cmdr
#        hostname: redis-commander
#        image: rediscommander/redis-commander:latest
#        depends_on:
#            - redis
#        environment:
#            REDIS_HOST: "redis"
#            REDIS_PORT: "6379"
#        ports:
#            - "8081:8081"

    pma:
        container_name: arcanesoft_pma
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        environment:
            MYSQL_USERNAME: "${DB_USERNAME}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            PMA_HOST: db
        depends_on:
            - db

volumes:
    db_data:
    redis_data:
